# Template for environment configuration
# Copy this file to .env and fill in your values

api_keys:
  openai: your_openai_api_key_here
  salesforce: your_salesforce_api_key_here

salesforce:
  instance_url: your_instance_url
  username: your_username
  password: your_password
  security_token: your_security_token

llm:
  model_name: gpt-4  # or other model name
  max_tokens: 2000
  temperature: 0.7

cache:
  enable_llm_cache: true
  cache_dir: .llm_cache
  embedding_cache_dir: .embedding_cache

debug:
  debug_mode: false
  debug_output_dir: debug_prompts

paths:
  raw_data: data/raw
  processed_data: data/processed
  output: data/output 